name:                i3-analytics
version:             0.1.0.0
github:              "rdnetto/i3-analytics"
license:             Apache
author:              "Renee D'Netto"
maintainer:          "rdnetto@gmail.com"
copyright:           "2020 Renee D'Netto"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/i3-analytics#readme>

dependencies:
- base >= 4.7 && < 5
- basic-prelude

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- PartialTypeSignatures
- ScopedTypeVariables

executables:
  i3-analytics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - attoparsec
    - bytestring
    - chronos
    - containers
    - directory
    - i3ipc
    - microlens
    - microlens-ghc
    - microlens-th
    - mtl
    - parser-combinators
    - optparse-applicative
    - safe
    - template-haskell
    - text
    - torsor
    - unordered-containers
